services:
  vue:
    build:
      target: vue_prod
      args:
        - VITE_SENTRY_DSN=${SENTRY_DSN}

  docs:
    build:
      target: docs_prod

  frankenphp:
    build:
      context: ./symfony
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      SENTRY_DSN: ${SENTRY_DSN}
    volumes:
      - ./symfony/docker/caddy/Caddyfile.prod:/etc/caddy/Caddyfile
      - ./symfony/docker/caddy/worker.Caddyfile:/etc/caddy/worker.Caddyfile
    networks:
      - idg-network
  nominatim:
    networks:
      - idg-network

networks:
  idg-network:
    name: idg_network
