services:
  frankenphp:
    ports: !override
      - ${HTTP_PORT:-80}:80
    networks:
      - idg-network
  postgres:
    networks:
      - idg-network
  nominatim:
    networks:
      - idg-network

networks:
  idg-network:
    name: idg_network